config/routes.rb
Rails.application.routes.draw do

  resources :callbacks
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  post 'twilio/message' => 'twilio#message'
  root 'callbacks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:slack]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController::Base

  require 'rubygems'
  require 'twilio-ruby'

  def index
  end

  end

app/controllers/callbacks_controller.rb
class CallbacksController < ApplicationController

  def failure
    redirect_to user_session_path, danger: "Something went wrong! Please sign in with Slack again."
  end

  def slack
    data = request.env["omniauth.auth"]
    @user = User.where(slack_id: data.uid).first_or_create! do |u|
          u.email       = data.info.email
          u.password    = SecureRandom.hex 64
          u.slack_data  = data.to_h.to_json
          u.slack_id    = data.uid
          u.token       = data[:credentials].token

    end

    sign_in @user
  end

  def update
    current_user.phone_number = params[:user][:phone_number]
    current_user.save
  end

end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

  def message
    current_user = User.where(phone_number: params[:From])
    HTTParty.post "https://slack.com/api/chat.postMessage",
    header: {
      "Authorization" => "token #{current_user.first.token}",
      "user-agent" => "something here"
    },
    query: {
      "token" => "#{current_user.first.token}",
      "channel" => '#general',
      "text" => params["Body"],
      "as_user" => true
      }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/index.html.erb
<h1>this is the layout</h1>

app/views/callbacks/failure.html.erb
<h1>you have failed!!!</h1>

app/views/callbacks/slack.html.erb
<h1>slack callbacks</h1>

<div class="form">
  <%= form_for @user, url: callback_path(@user), method: :patch do |f| %>
  <%= f.text_field :phone_number  %>
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Textslack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/twilio/message.html.erb
<h1>this is the phone number form</h1>